apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-ha
  namespace: argocd

  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  destination:
    namespace: circuit-breaker-app
    server: 'https://kubernetes.default.svc'

  sources:
    - repoURL: 'https://dandydeveloper.github.io/charts/'
      chart: redis-ha
      targetRevision: 4.32.0
      helm:
        valueFiles:
          - $values/values/values-dev.yaml
        skipSchemaValidation: false
        skipCrds: false

    - repoURL: 'git@github.com:evil-cloud/resillience-poc-cache-redis-k8s.git'
      targetRevision: HEAD
      ref: values

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
      - ignoreMissingValueFiles=true

    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  revisionHistoryLimit: 5
