apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-ha
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: redis
    server: 'https://kubernetes.default.svc'

  sources:
    - repoURL: 'git@github.com:evil-cloud/resillience-poc-cache-redis-k8s.git'
      targetRevision: main
      ref: values
      helm:
        valueFiles:
          - values/redis-values.yaml

  project: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true

