apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-ha
  namespace: argocd
spec:
  project: default
  destination:
    namespace: circuit-breaker-api
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: 'https://dandydeveloper.github.io/charts/'
      chart: redis-ha
      targetRevision: 4.4.2
      helm:
        valueFiles:
          - $values/values/values-dev.yaml
    - repoURL: 'git@github.com:evil-cloud/resillience-poc-cache-redis-k8s.git'
      targetRevision: HEAD
      ref: values

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

