apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-ha
  namespace: argocd
spec:
  project: default
  destination:
    namespace: redis
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: 'https://dandydeveloper.github.io/charts/'
      chart: redis-ha
      targetRevision: 4.4.2
      helm:
        valueFiles:
          - $values/values.yaml
    - repoURL: 'git@github.com:evil-cloud/circuit-breaker-app.git'
      targetRevision: main
      ref: values
      path: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

